# Mahcine Learning - Supervised Learning - Regression
# Linear Regression
## Part2: Linear Regression

## Reading Data

In [3]:
import numpy as np
import pandas as pd

In [15]:
df = pd.read_csv("Modified_Housing.csv")
df.head()

Unnamed: 0      area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0           0  0.651977         4          2        3         1          0   
1           1  0.825989         4          4        4         1          0   
2           2  0.938983         3          2        2         1          0   
3           3  0.661017         4          2        2         1          0   
4           4  0.651977         4          1        2         1          1   

   basement  hotwaterheating  airconditioning  parking  prefarea  \
0         0                0                1        2         1   
1         0                0                1        3         0   
2         1                0                0        2         1   
3         1                0                1        3         1   
4         1                0                1        2         0   

   furnishingstatus     price  
0                 0  13300000  
1                 0  12250000  
2                 1  12250000  
3                 0  12215000  
4                 0  11410000

In [27]:
df.columns[1]
df.drop([df.columns[0]], axis=1, inplace=True)
df.shape[1]

13

### 1- Regression Linear Equation

- for simplicity the Features (columns) will be given mathimatical variables such as X1, X2, ... as illustrated in the table below

|Index | Feature Name   | Variable Name |
|:----:|:-------------  |:--------------|
|0     |area            |$$x_1$$        |
|1     |bedrooms        |$$x_2$$        |
|2     |bathrooms       |$$x_3$$        |
|3     |stories         |$$x_4$$        |
|4     |mainroad        |$$x_5$$        |
|5     |guestroom       |$$x_6$$        |
|6     |basement        |$$x_7$$        |
|7     |hotwatereating  |$$x_8$$        |
|8     |airconditioning |$$x_9$$        |
|9     |parking         |$$x_{10}$$       |
|10    |prefarea        |$$x_{11}$$       |
|11    |furnishingstatus|$$x_{12}$$       |

- Target Feature is the "**price**" column and will be named as f(x) or y

- number of features (columns) is: **m** = 12

- sample size is: **n**

- linear equation of one data point will be:

  $f(x) = y = a_1x_1 + a_2x_2 + a_3x_3 + ... + a_mx_m + a_0 $
  
  $ $


- the equation above can be writen using matrices notation:

  ${\begin{bmatrix} y \end{bmatrix}}_{1x1} = {\begin{bmatrix} x_1 & x_2 & x_3 & \cdots & x_m & 1\end{bmatrix}}_{1x13} . {\begin{bmatrix} a_1 \\ a_2 \\ a_3 \\ \vdots \\ a_m \\ a_0 \end{bmatrix}}_{13x1} $

- the equation for all data points:

  ${\begin{bmatrix} y_1 \\ y_2 \\ y_3 \\ \vdots \\ y_n \end{bmatrix}}_{nx1} = {\begin{bmatrix} {x_1}_1 & {x_2}_1 & {x_3}_1 & \cdots & {x_m}_1 & 1 \\ {x_1}_2 & {x_2}_2 & {x_3}_2 & \cdots & {x_m}_2 & 1 \\ {x_1}_3 & {x_2}_3 & {x_3}_3 & \cdots & {x_m}_3 & 1 \\ \vdots & \vdots & \vdots & \vdots & \vdots & \vdots \\ {x_1}_n & {x_2}_n & {x_3}_n & \cdots & {x_m}_n & 1 \end{bmatrix}}_{nx13} . {\begin{bmatrix} a_1 \\ a_2 \\ a_3 \\ \vdots \\ a_m \\ a_0 \end{bmatrix}}_{13x1} $

- which is equivelant to:

  ${\begin{bmatrix} Target & Matrix \end{bmatrix}}_{nx1} = {\begin{bmatrix} y \end{bmatrix}}_{nx1} = {\begin{bmatrix} Features & Matrix \end{bmatrix}}_{nx(m+1)} . {\begin{bmatrix} Linear & Equation & Coefficients & Matrix \end{bmatrix}}_{(m+1)x1} .  $

### 2- Assuming  Linear Equation Coefficients

*Random matrix can be generated using numpy for the coefficients matrix*


### 3- Equation Evaluation & Finding Y Prediction ($\hat{y}$)

*by using the same equation of Target Matrix:* 

${\begin{bmatrix} \hat{y} \end{bmatrix}}_{nx1} = {\begin{bmatrix} Features & Matrix \end{bmatrix}}_{nx(m+1)} . {\begin{bmatrix} Assumed & Linear & Equation & Coefficients & Matrix \end{bmatrix}}_{(m+1)x1} .  $

### 4 - Calculating Mean Square Error (MSE)
$ {\begin{bmatrix} error \end{bmatrix}}_{nx1} = {\begin{bmatrix} y \end{bmatrix}}_{nx1} - {\begin{bmatrix} \hat{y} \end{bmatrix}}_{nx1} $

$MSE = {{\sum\limits_{i=0}^{n-1} {error^2}} \over n} = {{\sum\limits_{i=0}^{n-1} {(y-\hat{y})^2}} \over n} = {1 \over n} \Sigma {\begin{bmatrix} error^2 \end{bmatrix}}_{nx1} = {1 \over n} \Sigma ({\begin{bmatrix} y \end{bmatrix}}_{nx1} - {\begin{bmatrix} \hat{y} \end{bmatrix}}_{nx1})^2$

### 5- Gradient Descent Algorithm
- the following equation is for one point data and one coefficient (index =1 for instance)

  $a_{new_1} = a_1 - \alpha . { \delta MSE \over \delta a_1 } = a_1 - \alpha . { \delta {1 \over n} \sum\limits_{i=0}^{n-1} ({\begin{bmatrix} y_i \end{bmatrix}}_{nx1} - {\begin{bmatrix} \hat{y}_i \end{bmatrix}}_{nx1})^2 \over \delta a_1 } = a_1 - \alpha . {- 2 \over n} . \sum\limits_{i=0}^{n-1} {(y_i - \hat{y}_i). x_{i1}} = a_1 + {2 \alpha  \over n} . \sum\limits_{i=0}^{n-1} {x_{i1}(y_i - \hat{y}_i)} $


- for any index either point data (record) or feature (column)
  
  $a_{new_j} = a_j - \alpha . { \delta MSE \over \delta a_j } = a_j - \alpha . { \delta {1 \over n} \sum\limits_{i=0}^{n-1} ({\begin{bmatrix} y_i \end{bmatrix}}_{nx1} - {\begin{bmatrix} \hat{y}_i \end{bmatrix}}_{nx1})^2 \over \delta a_j } = a_j + {2 \alpha  \over n} . \sum\limits_{i=0,j=0}^{n-1,m} {x_{ij}(y_i - \hat{y}_i)}$ 

   where,
          - $ \alpha $ is the learning rate 
          
          - i: looping index for sample records (0 to n-1)
          
          - j: looping index for features columns (0 to m)
          
- the equation for all coefficeints is:

  $ {\begin{bmatrix} {a_{new}}_1 \\ {a_{new}}_2 \\ \vdots \\ {a_{new}}_{12} \\ {a_{new}}_0  \end{bmatrix}}_{13x1}= {\begin{bmatrix} a_1 \\ a_2 \\ \vdots \\ a_{12} \\ a_0  \end{bmatrix}}_{13x1} + {2\alpha \over n} . {\begin{bmatrix} \sum\limits_{i=0}^{n-1} {x_{i1}(y_i - \hat{y}_i)} \\ \sum\limits_{i=0}^{n-1} {x_{i2}(y_i - \hat{y}_i)} \\ \vdots \\ \sum\limits_{i=0}^{n-1} {x_{i12}(y_i - \hat{y}_i)} \\ \sum\limits_{i=0}^{n-1} {(y_i - \hat{y}_i)}  \end{bmatrix}}_{13x1} $
  
- in another way:

  ${\begin{bmatrix} new & coeffiecient & Matrix \end{bmatrix}}_{m+1x1} = {\begin{bmatrix} coeffiecient & Matrix \end{bmatrix}}_{m+1x1} + {2\alpha \over n} . {\begin{bmatrix} MSE & / & coefficient & derivative & Matrix \end{bmatrix}}_{m+1x1} $


---

## Class Implementation
### Class Members
#### Public Members:
- **num_iterations**: number of iterations
- **lr** : learning rate
- **df** : data frame that contains sample

#### Private members
- **n**: sample numbers
- **coeff_mat**: coefficient matrix (m+1 x1)
- **features_mat**: features matrix (n x m+1)
- **y** : target matrix (n x 1)

### Class Methods
#### Public Methods
- **__init__** : constructor get the public members and produces the private members
- **Fit**: run perform training and get the training model
- **Predict**: use the training model to get houses price

#### Private Methods
- **y_hat** : return the predicted values
- **ErrorCalc** : return the error and MSE
- **DMat**: return the derivitave matrix
- **GD**: Gradient Descent Algoritm , returns the final coefficeint matrix

In [32]:
import numpy as np
import pandas as pd

In [410]:
class LinearRegression:
    def __init__(self, df, lr=0.01, num_iterations=1000):
        # public members
        
        self.df = pd.DataFrame(df) 
        
        self.lr = lr
        
        self.num_iterations = num_iterations
        
        # private members
        
        self.n = self.df.shape[0]
        
        self.m = self.df.shape[1]-1
        
        np.random.seed()
        self.coeff_mat = np.random.rand(self.m+1,1)
        
        self.features_mat = np.random.rand(self.n,self.m+1)
        self.features_mat[:,:-1] = df.iloc[:,:-1].values
        self.features_mat[:,-1] = np.ones((self.n,1)).T
        
        self.y = df.iloc[:,-1:].values
    
    #Private Methods
    
    def y_hat(self,features_mat):
        return features_mat.dot(self.coeff_mat)
    
    def ErroCalc(self):
        
        error = self.y - self.y_hat(self.features_mat)
        
        MSE = np.mean(error**2)
        
        return (error, MSE)
    
    def DMat(self):
        error = self.ErroCalc()[0]
        mat = np.random.rand(self.m+1,1)
        for i in range(0,mat.shape[0]):
            temp_mat = error * self.features_mat[:,i:i+1]
            mat[i,0] = temp_mat.sum()
        
        return mat
    
    def GD(self):
        self.coeff_mat = self.coeff_mat + (2 * self.lr / self.n) * self.DMat()
        
    #Public Functions
    
    def Fit(self, tolerance=0.01):
        
        for i in range(self.num_iterations):
            
            err = self.ErroCalc()[1]
            
            if err <= tolerance:
                print(f"Reached accepted tolerance of error = {err} in iteration no: {i}")
                break
            
            self.GD()
            
    def Predict(self, df_features):
        
        mat = np.random.rand(df_features.shape[0],self.m+1)
        mat[:,:-1] = df_features.iloc[:,:].values
        mat[:,-1] = np.ones((mat.shape[0],1)).T
        
        return self.y_hat(mat)
            
    

In [411]:
test = LinearRegression(df)

In [412]:
test.coeff_mat

array([[0.27989317],
       [0.31807574],
       [0.64072371],
       [0.7550595 ],
       [0.10254791],
       [0.21427501],
       [0.57321409],
       [0.56513806],
       [0.21419936],
       [0.41019267],
       [0.26707199],
       [0.55152911],
       [0.39246393]])

In [413]:
test.Fit(100000)
test.coeff_mat

array([[1397319.28873173],
       [ 174221.47042447],
       [1043640.72435085],
       [ 428256.23651017],
       [ 600587.92495332],
       [ 341053.00189276],
       [ 328388.69818429],
       [ 470095.95119173],
       [ 862229.22536763],
       [ 345735.29408939],
       [ 696864.02597036],
       [-216134.35010169],
       [ 429047.1907982 ]])

In [420]:
test.ErroCalc()[1]

1163409393356.7866

**Note:**
*Very big error!, this means either equation or code need to be reviewed*

In [415]:
test.Predict(df.iloc[:,:-1])

array([[ 8260155.59361442],
       [10667713.89210317],
       [ 7308741.53972002],
       [ 8518654.48419134],
       [ 6760836.3068601 ],
       [ 8397947.85741647],
       [ 9699069.65916796],
       [ 6853227.70247509],
       [ 7565064.97874431],
       [ 7813564.4280705 ],
       [ 7428724.5508289 ],
       [ 8015647.48834646],
       [ 7132666.12181751],
       [ 6123976.45110169],
       [ 5947841.6133953 ],
       [ 5117217.08656027],
       [ 7593867.93105124],
       [ 7987846.65371059],
       [ 6856619.36043005],
       [ 6937919.05732127],
       [ 5147837.73624626],
       [ 6727889.99000356],
       [ 5912093.49249155],
       [ 6832957.19711825],
       [ 7178700.93624048],
       [ 8362398.57423397],
       [ 8051824.47855894],
       [ 4294546.7947083 ],
       [ 6896924.79350211],
       [ 7295271.175576  ],
       [ 7393741.53871058],
       [ 6491237.8015069 ],
       [ 7085125.5326896 ],
       [ 6803144.85513248],
       [ 6497746.75579806],
       [ 7751012.875