# Data Science Preparation 
## NumPy Assignment


In [6]:
import numpy as np

### 1. Write a NumPy program to test whether none of the elements of a given array is zero.

In [21]:
# input array
mat1 = np.random.randint(-10, 11, (5, 5))
mat2 = np.random.randint(1, 11, (5, 5))

In [22]:
def IsNoneZeroElement(mat):
    return np.all(mat!=0)

In [23]:
print(f"The first matrix is :\n {mat1}")
print(f"All Elements is none Zero ? {IsNoneZeroElement(mat1)}")
print("======================")
print(f"All Elements is none Zero ? :\n {mat2}")
print(f"Contains Zero ? {IsNoneZeroElement(mat2)}")

The first matrix is :
 [[  2  -6  -6   8 -10]
 [  0  -4  -3   7  -7]
 [  1  -9  -9   6  -3]
 [ 10   3   6   0   6]
 [ -8   4   1   7   2]]
All Elements is none Zero ? False
All Elements is none Zero ? :
 [[ 9  3  3 10  6]
 [ 5  9  3  7  2]
 [ 9  1  4  3  4]
 [ 3  1  6 10 10]
 [10 10  5  8  8]]
Contains Zero ? True


### 2. Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [29]:
# input array
mat1 = np.random.randint(-10, 11, (5, 5))
mat2 = np.random.randint(1, 11, (5, 5))

In [30]:
def IsAnyZeroElement(mat):
    return np.any(mat==0)

In [31]:
print(f"The first matrix is :\n {mat1}")
print(f"Any Elements is Zero ? {IsAnyZeroElement(mat1)}")
print("======================")
print(f"The first matrix is :\n {mat2}")
print(f"Any Elements is Zero ? {IsAnyZeroElement(mat2)}")

The first matrix is :
 [[  1   3   8  -5  -4]
 [  1  -1  -6 -10   6]
 [ 10  -2   1   0  -7]
 [-10  -3   4   2   7]
 [  4   4  -7   3   0]]
Any Elements is Zero ? True
The first matrix is :
 [[ 1  6  5  7  9]
 [ 9  6  7  6  8]
 [10 10 10  8  6]
 [ 3  7  9  3  9]
 [ 8  8  2 10  8]]
Any Elements is Zero ? False


### 3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given 

In [59]:
# input
lst1 = np.linspace(0, 3, num=20)
lst2 = np.linspace(0, 4, num=20)
tolerance =0.5

In [60]:
print(f"lst1 : {lst1}")
print()
print(f"lst1 : {lst1}")
print(lst1 == lst2)
print()
print(np.isclose(lst1, lst2, tolerance))


lst1 : [0.         0.15789474 0.31578947 0.47368421 0.63157895 0.78947368
 0.94736842 1.10526316 1.26315789 1.42105263 1.57894737 1.73684211
 1.89473684 2.05263158 2.21052632 2.36842105 2.52631579 2.68421053
 2.84210526 3.        ]

lst1 : [0.         0.15789474 0.31578947 0.47368421 0.63157895 0.78947368
 0.94736842 1.10526316 1.26315789 1.42105263 1.57894737 1.73684211
 1.89473684 2.05263158 2.21052632 2.36842105 2.52631579 2.68421053
 2.84210526 3.        ]
[ True False False False False False False False False False False False
 False False False False False False False False]

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]


### 4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [66]:
print("Zeros array")
print(np.zeros((10)))
print("Ones array")
print(np.ones((10,)))
print("fives array")
print(np.full((10,),5))

Zeros array
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Ones array
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
fives array
[5 5 5 5 5 5 5 5 5 5]


### 5. Write a NumPy program to create an array of the integers from 30 to70.

In [67]:
np.arange(30,71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

### 6. Write a NumPy program to create a 3x3 identity matrix 

In [71]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 7. Write a NumPy program to generate a random number between 0 and 1

In [74]:
np.random.rand()

0.06166469985749745

### 8. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [84]:
lst = np.random.randn(15)
print(lst)

[ 0.52206977  0.78150939  0.28741615  0.17709012  0.16469905  0.45436486
 -0.08389511 -1.5641167  -1.28048347  0.48274769 -0.68099793 -1.18278605
  0.33984656  1.81277854 -0.7362505 ]


In [85]:
print(f" list mean:  {lst.mean()}")
print(f" list standard deviation: {lst.std()}")
print(f" -2 * std: {-2*lst.std()} and 2 * std: {2*lst.std()}")

 list mean:  -0.03373384271288143
 list standard deviation: 0.869729328279845
 -2 * std: -1.73945865655969 and 2 * std: 1.73945865655969


### 9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [87]:
vector = np.arange(15,56)
print(vector[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


### 10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [88]:
np.random.randint(0, 10, (5,))

array([5, 2, 8, 8, 0])

### 11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [97]:
# create 10x10 ones matrix
mat = np.ones((10,10),np.int8)
print(f"one matrix is:\n {mat}")
# setting all elements except borders by 0
mat[1:-1,1:-1] = 0
print(f"final matrix is:\n {mat}")

one matrix is:
 [[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
final matrix is:
 [[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


### 12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.


In [104]:
# create matrix diagonal
diag = np.arange(1,6)
print(f"the matrix diagonal is: {diag}")

# create the 5x5 matrix
dMat = np.diag(diag)
print(f"the diagonal matrix is:\n{dMat}")

the matrix diagonal is: [1 2 3 4 5]
the diagonal matrix is:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


### 13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.


In [121]:
# Assumption: the staggered matrix will start by 0 in the upper left corner (element[0,0])

# step1: create 4x4 ones matrix
mat = np.ones((4,4))
print(f"step1(ones matrix):\n{mat}")

# step2: assining staggered zeros using step = 2 
mat[::2,::2] = 0
print(f"step2(staggered matrix):\n{mat}")

# step3: changing diagonal to zeros based in where comparison of 2 matrices 
# create diagonal matrix to be used as a condition
diag = np.ones((mat.shape[0],))
print("step3:")
print(f"step3-1: the diagonal: {diag}")
dMat = np.diag(diag)
print(f"step3-2: the diagonal:\n{dMat}")
mat = np.where(dMat == 1, 0, mat)
print(f"step3-3: Final matrix:\n{mat}")


step1(ones matrix):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
step2(staggered matrix):
[[0. 1. 0. 1.]
 [1. 1. 1. 1.]
 [0. 1. 0. 1.]
 [1. 1. 1. 1.]]
step3:
step3-1: the diagonal: [1. 1. 1. 1.]
step3-2: the diagonal:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
step3-3: Final matrix:
[[0. 1. 0. 1.]
 [1. 0. 1. 1.]
 [0. 1. 0. 1.]
 [1. 1. 1. 0.]]


### 14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.


In [125]:
mat1 = np.full((4,4),5)
mat2 = np.full((4,4),3)
# save the matrices
np.savez('d:\\file.npz', Mat_1=mat1, Mat_2=mat2)

In [126]:
#Load both matrices
with np.load('d:\\file.npz') as file:
    Mat1 = file['Mat_1']
    Mat2 = file['Mat_2']
    print(Mat1)
    print("-------")
    print(Mat2)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
-------
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


### 16. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number

In [127]:
#create
arr = np.random.randint(0,20,(5,5))
print(arr)

[[12 12 10  0 12]
 [ 2 13  9  7  5]
 [19  9  3  7 19]
 [ 4  5  3  5  6]
 [ 8 16  1 13 12]]


In [130]:
#values greater than 10
arr[arr > 10]

array([12, 12, 12, 13, 19, 19, 16, 13, 12])